apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: NOME DA IMAGEM DO REPOSITORIO DO DOCKERHUB AQUI
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: auth-configmap
        resources:
            requests:
              cpu: 400m
